name: Build and Deploy Node.js app to Azure Web App - CyberRiskPortal

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  AZURE_WEBAPP_NAME: 'CyberRiskPortal' # your Azure Web App name
  AZURE_SLOT_NAME: 'Production' # deployment slot (default Production)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3️⃣ Clean and build project
      - name: Install dependencies and build
        run: |
          rm -rf dist
          npm ci
          npm run build --if-present
          npm run test --if-present

      # 4️⃣ Upload entire project (includes dist/, package.json, etc.)
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # 1️⃣ Download artifact from build job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      # 2️⃣ Login to Azure using federated credentials
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D47E8D630CEF4ADCA881E5229878BC0A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C8B19C00A9FB487497D98B13210E0A56 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_36C8FB6C28D140ACA0CF69BF75A71CD1 }}

      # 3️⃣ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_SLOT_NAME }}
          package: .

      # 4️⃣ Logout
      - name: Logout of Azure
        run: az logout
